function [fitresult, gof] = createFit(F, z)
%CREATEFIT(F,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : F
%      Y Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
%  Auto-generated by MATLAB on 21-Jan-2018 16:14:53
%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( F, z );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'z vs. F', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel F
% ylabel z
% grid on


